#index:
#    path: /
#    controller: App\Controller\DefaultController::index

guideMichelin_accueil:
  path: /accueil/{nom}
  controller: App\Controller\MichelinController::accueil
  defaults:
    nom: ""
guideMichelin_menu:
  path: /menu
  controller: App\Controller\MichelinController::menu
